function FileMover(app,filename,mode)
%FILEMOVER Moves files generated by functions to a new folder
path = [app.SavePath '/MatlabResultsFile'];
if exist(path,'dir')==0;mkdir(path);end

%if no mode was expliced place the file onto the file created & exit
if nargin<3;movefile(filename,path);return;end

%Check modes
switch upper(mode)
    case 'ANI';     str = 'Anisotropy';
    case 'BSCINF';  str = 'BasicInfo';
    case 'CONTNBR';	str = 'ContactNumber';
    case 'FORCE';   str = 'Forces';
    case 'FC';      str = 'ForceChain';
    case 'FCCL';    str = 'ForceChain/Cluster';
    case 'FORCEXT'; str = 'ForcesEXT';
    case 'LOOPS';   str = 'Loops';
    case 'LOOPA';   str = 'Loops/Anisotropy';
    case 'LOOPH';   str = 'Loops/Histogram';
    case 'LOOPHL';	str = 'Loops/Histogram/Load';
    case 'LOOPL';   str = 'Loops/Load';
    case 'LOOPVR';  str = 'Loops/VoidRatio';
    case 'VOID';	str = 'Voidratio-Porosity';
    case 'STRAIN';  str = 'Strain';
end
path=[path '/' str];

%test existence of the file and create it if necessary
if exist(path,'dir')==0;mkdir(path);end
movefile(filename,path);
end

