function path=MakePath(app,mode,varargin)
%FILEMOVER Moves files generated by functions to a new folder
if strcmp(app.SavePath(end),'/') 
    path = fullfile(app.SavePath,'MatlabResultsFile/');
else
    path = fullfile(app.SavePath,'/MatlabResultsFile/');
end

%if no mode was expliced return base file
if nargin==1 || isempty(mode);return;end

%Check modes
switch upper(mode)
    case 'ANI';     str = 'Anisotropy';
    case 'BSCINF';  str = 'BasicInfo';
    case 'CONTNBR';	str = 'ContactNumber';
    case 'DPL';     str = 'DisplacementVTK';
    case 'EDG';     str = 'Edges';
    case 'FC';      str = 'ForceChain';
    case 'FCL';     str = 'ForceChain/Load';
    case 'FCCL';    str = 'ForceChain/Cluster';
    case 'FCCLTF';  str = 'ForceChain/ClusterTransf';
    case 'FORCE';   str = 'Forces';
    case 'FORCEXT'; str = 'ForcesExt';
    case 'FORCEXTL';str = 'ForcesExt/Load';
    case 'LOOPS';   str = 'Loops/General';
    case 'LOOPL';   str = 'Loops/General/Load';
    case 'LOOPAC';  str = 'Loops/AveCluster';
    case 'LOOPA';   str = 'Loops/Anisotropy';
    case 'LOOPAL';  str = 'Loops/Anisotropy/Load';
    case 'LOOPCT';  str = 'Loops/ClusterTransformation';
    case 'LOOPER';  str = 'Loops/ErrorContact';
    case 'LOOPD';   str = 'Loops/Deformability';
    case 'LOOPDL';	str = 'Loops/Deformability/Load';
    case 'LOOPDCL'; str = 'Loops/Deformability/Cluster';
    case 'LOOPST';  str = 'Loops/Stress';
    case 'LOOPVR';  str = 'Loops/VoidRatio';
    case 'LOOPVRL'; str = 'Loops/VoidRatio/Load';
    case 'LOOPVRCL';str = 'Loops/VoidRatio/Cluster';
    case 'VOID';	str = 'Voidratio-Porosity';
    case 'VOIDL';	str = 'Voidratio-Porosity/Load';
    case 'STRAIN';  str = 'Strain';
    case 'STNCL';   str = 'Strain/StrainCluster';
    case 'STNW2AC'; str = 'Strain/W2AveCl';
    case 'SCF';     str = 'SpaceCellFiles';
    otherwise;      str='';
end
path=fullfile(path,str,'/');

%test existence of the file and create it if necessary
if nargin<3;if exist(path,'dir')==0;mkdir(path);end;end
end

